### ISSUE TITLE
Peer Evaluation - Portfolio Pattern Library

### ISSUE THREAD

**Issue by MichaelaRob** [Jowens96/portfolio#2]
Pattern Library looks great so far. I like the different colours used which represent your brand. Great responsiveness. Typography choices are great as well, they provide good contrast from one another. I think the idea of having your reel automatically play when users visit your website is a great idea as well as having the volume muted since you don't want to attack anyone with sound. Looking forward to seeing the finished product!

**Comment by Jowens96** [comment]
Thank you :)
