### ISSUE TITLE
Pattern Library Feedback

### ISSUE THREAD

**Issue by patricia568** [Jowens96/portfolio#3]
Hi Jenny!

Everything looks really well done on your website! I think your style is reflected very well throughout the website, which is great! I think you should try making your hover colour more of a lighter shade of red so that it stands out more from the black background. But everything looks fantastic so far! Great job!

- Patricia

**Comment by Jowens96** [comment]
Hi Patricia, I have lightened the red for better contrast. I checked the contrast ratio through WebAIM and it is sufficiently contrasted! Woo-hoo!
