### ISSUE TITLE
Pattern Library Feedback 

### ISSUE THREAD

**Issue by jiannanolan** [Jowens96/portfolio#4]
Well implemented structure and grid. It is really creative how the banners change between using photography and video. The monocromative pallete will help showcase the colours found within the imagery and will not be too distracting which is really effective. One suggestion would be to create greater contrast between headers and content, maybe increasing the sizing? The illustrations are really nice tie the colour pallette together nicely. Well done!

**Comment by Jowens96** [comment]
Hi Jianna, thanks for the positive feedback. I have lightened the red colour for better contrast, and increased the sizing of headers for better typographic hierarchy. Best of luck in your continued work on your site!
