### ISSUE TITLE
Portfolio Review!

### ISSUE THREAD

**Issue by sander-aaron** [Jowens96/portfolio#7]
Hi Jenny,

You're site looks great! There are a few things I would adjust stated down below.
Cthulbru - I would suggest having the images smaller on larger sizes, maybe add a wrapper if you want to keep the single layout or a grid.
On the vimeo links, you can change the blue on the links to your own colour so it isn't distracting.
Also, on your about page, your email can be a link if you add href="mailto:jenny.anne.owens@gmail.com"

**Comment by Jowens96** [comment]
Hi Aaron,

I have added a grid to the cthulbru page, changed the colour of vimeo links to red, and added a mail-to to my about page.

Thank you!
