### ISSUE TITLE
Your website

### ISSUE THREAD

**Issue by Miriampion** [Jowens96/portfolio#8]
Great website, I think it flows well and will look really good when you add the banner. At screen size 768, the buzz paragraph looks a little skinny, so maybe just look at that.
Otherwise, I like the large photos, they are very nice!

**Comment by Jowens96** [comment]
Hi Miriam,

I took a look and you're right, the about page looked very strange. I put all the text into one column so it's not forced into such a small space. The text is able to spread out more now. I gave it a max length of 25em so the line length isn't too long.

Thank you!
