### ISSUE TITLE
Portfolio Review

### ISSUE THREAD

**Issue by jiannanolan** [Jowens96/portfolio#9]
Hi Jenny, 

I really like the construction and the look of your site. I thought the way you used a minimal colour palette and black background really makes the works pop and incorporates a style that really pairs nicely with the pieces you feature. I also thought your animation and hover links on your works page were really effective and made the page interesting and engaging to explore. 

Suggestions I would recommend are to maybe create rows of 2 for the work on the medium screen so that the works don't get too tight. Also perhaps change the colour of your top navigation to be either black or a more vibrant red as right now it is so dark the red isn't noticable but looks a little unintentional. Maybe consider adding imagery on your about page? And lastly maybe consider adding a favicon to your site since you have a really cool and unique logo!

Overall really well done! I look forward to seeing the completed version with the motion banners :)

**Comment by Jowens96** [comment]
Hi Jianna,

Thank you for the helpful feedback - I appreciate the compliments :)

I have created a grid for the cthulbru photos so they don't display huge on large screens. I changed the top navigation to pure black so the navigation is more clear. I added a picture of myself on the about page, and I am about to begin adding a favicon.

Have a great night!
